version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t flask-app .
      - docker tag flask-app:latest $ECR_REGISTRY/flask-repo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ECR_REGISTRY/flask-repo:latest
      - echo Writing image definitions file...
      - printf '[{"name":"flask-app","imageUri":"%s"}]' $ECR_REGISTRY/flask-repo:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json